### ISSUE TITLE
Save File Pre-Delay

### ISSUE THREAD

**Issue by SchuylerTowne** [gcollazo/BrowserRefresh-Sublime#31]
I'm using the browser-refresh plugin in concert with the Sublime SFTP plugin.

Ideally anytime I use the browser refresh key binding my file would save, which triggers SFTP to upload it, then the delay I have set in my preferences would be carried out, to give the upload time to finish, then the browser refreshes. 

Presently the save appears to take place after the delay and my browser often beats the upload so I have to either re-reload or save, then refresh.

Obviously saving manually before refreshing isn't a huge deal, and I love the plugin. Thanks for any consideration!

**Comment by LikeTazman** [comment]
Just add a greater 'delay' at keymap-user. 
For example, at default keymap it was set as "0.5" and I was having the same problem (no refresh), although it was refreshing after pressing ctrl+shift+r twice (save+save...).
Then I increase the delay at user side to "1.0" and is refreshing perfectly.
