### ISSUE TITLE
Can't change keybinding

### ISSUE THREAD

**Issue by renodesper** [gcollazo/BrowserRefresh-Sublime#54]
I'm using emmet and it has a keybinding conflict with BrowserRefresh in Preferences > Key Bindings - User. I already tried changing the keybinding into "command+shift+x" but FindKeyConflict still show me "command+shift+r".

**Comment by michael-wise** [comment]
I changed the binding in Preferences -> Key Bindings -> User to avoid conflict with Emmet's 'change value for all vendor prefixes.' Ctrl+Shift+R still activates BrowserRefresh. It would be helpful to have a note in Readme to save time if this is a known issue.

`[
    {
      "keys": ["ctrl+shift+,+ctrl+shift+r"], "command": "browser_refresh", "args": {
        "auto_save": true,
        "delay": 0.1,
        "activate": true,
        "browsers" : ["chrome"]
      }
    }
  ]`
