### ISSUE TITLE
Support for Firefox Developer Edition

### ISSUE THREAD

**Issue by AlexKvazos** [gcollazo/BrowserRefresh-Sublime#66]
Are there any plans to add support for Firefox Developer Edition?

Thanks,
Alex

**Comment by waldbach** [comment]
I just stumbled on this issue as well, glad to help as long as I know what to do.

**Comment by gcollazo** [comment]
@waldbach This are the basic things that need to be donde to support a new browser. I'm assuming you are on a Mac.

First you have to create a regex to detect if the browser is running https://github.com/gcollazo/BrowserRefresh-Sublime/blob/master/mac/utils.py

Then make an AppleScript that will actually refresh the browser
https://github.com/gcollazo/BrowserRefresh-Sublime/blob/master/mac/__init__.py

Finally hook everything up in the main plugin file and make sure you test different settings
https://github.com/gcollazo/BrowserRefresh-Sublime/blob/master/BrowserRefresh.py

**Comment by waldbach** [comment]
Thanks, I fiddled with those locally, yesterday. But I guess I could not get the naming right for the Developer Edition. I will try again, cheers!

**Comment by gcollazo** [comment]
That should be the regex for the search.

```python
if re.search('FirefoxDeveloperEdition\.app', ps) is not None:
    running_browsers.append('firefoxdeved')
```

**Comment by waldbach** [comment]
Ah, that's very close to what I had yesterday. Will try this, thanks!

**Comment by gcollazo** [comment]
This should be the AppleScript. If it doesn't work you should try adding a `delay 0.1` after the `activate` instruction.

```applescript
tell application "FirefoxDeveloperEdition"
	activate
	tell application "System Events" to keystroke "r" using command down
end tell
```

**Comment by waldbach** [comment]
For the Apple script I had this:
`    def firefoxdeved(self):
        command = """
            tell application "FirefoxDeveloperEdition"
                activate
                tell application "System Events" to keystroke "r" using command down
            end tell
            """

        if 'firefoxdeved' in self.browsers:
            self._call_applescript(command)`

**Comment by waldbach** [comment]
Not working, yet...

In `BrowserRefresh.py` I have the following:

```python
        elif browser_name == 'FirefoxDeveloperEdition':
            refresher.firefoxdeved()
```

and

```python
        elif browser_name == 'all':
            refresher.chrome()
            refresher.safari()
            refresher.firefox()
            refresher.opera()
            refresher.firefoxdeved()
```

**Comment by waldbach** [comment]
Also in `utils.py` I have
```python
    if re.search(b'FirefoxDeveloperEdition\.app', ps) is not None:
        running_browsers.append('firefoxdeved')
```
not the `b` before `'FirefoxDevel...`
I tried with and without. Close, but no cigar, yet.

**Comment by waldbach** [comment]
In `__init__.py` I have the following now:

```python
    def firefoxdeved(self):
        command = """
            tell application "FirefoxDeveloperEdition"
                activate
                delay 0.1
                tell application "System Events" to keystroke "r" using command down
            end tell
            """

        if 'firefoxdeved' in self.browsers:
            self._call_applescript(command)
```

**Comment by waldbach** [comment]
My apologies for the struggle here, I know little to none about Python.

**Comment by gcollazo** [comment]
That commit adds the feature. I'll try to release a new version as soon as possible.

**Comment by gcollazo** [comment]
Ok, the new version is up

https://packagecontrol.io/packages/Browser%20Refresh

**Comment by waldbach** [comment]
Fantastic. Thanks a lot, Giovanni!

**Comment by waldbach** [comment]
There seems to be a bug where Safari starts up when it's not running on refresh. Firefox Dev Ed is refreshing after that.
For now I commented out Safari, since I don't use that for testing.

In `BrowserRefresh.py` I commented out:
```python
        elif browser_name == 'all':
            refresher.chrome()
           # refresher.safari()
            refresher.firefox()
            refresher.opera()
```

Now it all works fine! :)
